--- # TODO: move to / use from config flow - used as default values

# M-TEC espressif MODBUS server
MODBUS_IP : espressif.local     # IP address / hostname of "espressif" modbus server
MODBUS_PORT : 5743              # Port (usually no change required)
MODBUS_SLAVE : 252              # Modbus slave id (usually no change required)
MODBUS_TIMEOUT : 5              # Timeout for Modbus server (s)
MODBUS_RETRIES : 3              # Retries
MODBUS_FRAMER: rtu              # Modbus Framer (usually no change required; options: 'ascii', 'binary', 'rtu', 'socket', 'tls')

# Refresh interval
REFRESH_NOW_S     : 10          # Refresh "now" data every N seconds
REFRESH_DAY_M     : 5           # Refresh "day" statistic every N minutes
REFRESH_TOTAL_M   : 5           # Refresh "total" statistic every N minutes
REFRESH_CONFIG_M  : 60          # Refresh "config" data every N minutes

# Define which extended data shall get included
ENABLE_GRID_DATA : False        # Extended grid data
ENABLE_INVERTER_DATA : False    # Extended inverter data
ENABLE_BACKUP_DATA : False      # Extended backup data
ENABLE_BATTERY_DATA : False     # Extended battery data
ENABLE_PV_DATA : False          # Extended PV data

# Home Assistent support
HASS_ENABLE : True             # Enable home assistant
HASS_BASE_TOPIC : homeassistant # Basis MQTT topic of home assistant

# General
DEBUG : False                   # Set to True to get verbose debug messages
